name: Deploy to SAP BTP Cloud Foundry

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a fresh Ubuntu environment for each job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checkout the latest code from the repository

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Install Node.js, required for mbt
        with:
          node-version: '18' # Use a stable LTS version of Node.js

      - name: Install Cloud Foundry CLI
        run: |
          # Download the Cloud Foundry CLI binary
          wget -q -O cf-cli-installer.deb "https://packages.cloudfoundry.org/stable?release=debian64&version=8.7.6&source=github"
          # Install the CLI
          sudo dpkg -i cf-cli-installer.deb
          # Verify installation
          cf version

      - name: Install Cloud Foundry MultiApps Plugin
        run: |
          # Install the MultiApps plugin from the CF Community repository
          cf install-plugin -r CF-Community "multiapps" -f
          # Verify plugin installation
          cf plugins

      - name: Install MTA Build Tool (MBT)
        run: npm install -g mbt@1.2.0

      # --- Cloud Foundry Deployment Steps ---
      - name: Login to Cloud Foundry
        run: |
          echo "Attempting CF login with API endpoint: $CF_API_ENDPOINT"
          cf api $CF_API_ENDPOINT
          cf auth "$CF_USERNAME" "$CF_PASSWORD"
          cf target -o "$CF_ORG" -s "$CF_SPACE"
        env:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_API_ENDPOINT: ${{ secrets.CF_API_ENDPOINT }}

      - name: Push Backend Application
        run: |
          # Push the backend application
          # The manifest.yml here is implicitly used, or you can create one.
          # Ensure the app name 'pm-analyzer-backend' matches service-name in mta.yaml
          cf push pm-analyzer-backend -f manifest.yml --no-start # Push but don't start yet
        working-directory: ./backend # Set working directory for cf push

      - name: Start Backend Application
        run: |
          # Start the backend application after push
          cf start pm-analyzer-backend
        working-directory: . # Run from root

      - name: Build MTA Archive
        run: |
          mkdir -p mta_archives
          mbt build -p=cf --mtar mta_archives/com.sap.pm.pmanalyzer_1.0.0.mtar
          mv mta_archives/mta_archives/com.sap.pm.pmanalyzer_1.0.0.mtar mta_archives/
        working-directory: .

      - name: List MTAR files for debugging
        run: |
          echo "--- Listing contents of mta_archives/ ---"
          ls -l mta_archives/
          echo "--- End of mta_archives/ listing ---"
        working-directory: .

      - name: Deploy MTA Archive
        run: cf deploy mta_archives/com.sap.pm.pmanalyzer_1.0.0.mtar -f --retries 1
