name: Deploy Simple Fiori App to BTP

on:
  push:
    branches: [ feature/simple-btp-deploy ]
    paths:
      - 'simple-fiori-app/**'
      - 'approuter/**'
      - '.github/workflows/**'
      - 'mta.yaml'
      - 'xs-security.json'
      - 'package.json'
      - 'package-lock.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install All Dependencies
        run: npm install

      - name: Build UI5 App
        run: npx ui5 build --clean-dest --dest dist
        working-directory: simple-fiori-app

      - name: Install Cloud Foundry CLI v8 and Multiapps Plugin
        run: |
          wget -q -O cf8-cli.tgz "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v8"
          tar -zxvf cf8-cli.tgz
          mv cf8 /usr/local/bin/cf
          cf install-plugin -f multiapps
          cf --version

      - name: Login to SAP BTP
        run: |
          cf login -a "${{ secrets.CF_API }}" -u "${{ secrets.CF_USERNAME }}" -p "${{ secrets.CF_PASSWORD }}" -o "${{ secrets.CF_ORG }}" -s "${{ secrets.CF_SPACE }}"

      - name: Build MTA archive
        run: npx mbt build -p=cf

      - name: Deploy to SAP BTP
        run: cf deploy mta_archives/*.mtar -f