name: Deploy Simple Fiori App to BTP

on:
  push:
    branches: [ feature/simple-btp-deploy ]
    paths:
      - 'simple-fiori-app/**'
      - '.github/workflows/**' # NEU: Löst auch bei Änderungen am Workflow selbst aus

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install build and deploy tools
        run: npm install -g mbt cf-cli-v8

      - name: Login to SAP BTP
        run: |
          cf login -a "${{ secrets.BTP_CF_API_URL }}" -u "${{ secrets.BTP_CF_USERNAME }}" -p "${{ secrets.BTP_CF_PASSWORD }}" -o "${{ secrets.BTP_CF_ORG }}" -s "${{ secrets.BTP_CF_SPACE }}"

      - name: Build MTA archive
        run: mbt build -p=cf
        working-directory: simple-fiori-app

      - name: Deploy to SAP BTP
        run: cf deploy simple-fiori-app/mta_archives/simple-fiori-app_1.0.0.mtar -f