name: Build and Deploy to BTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pm-analyzer-backend:latest
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install MTA Build Tool
        run: npm install -g mbt

      - name: Build MTA
        run: mbt build -p=cf
        working-directory: ./pm-analyzer-fiori
        
      # --- DEPLOYMENT STEPS (REPLACED) ---
      - name: Install Cloud Foundry CLI
        run: |
          wget -q -O - https://packages.cloud.foundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloud.foundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf8-cli

      - name: Deploy to BTP Cloud Foundry using CLI
        run: |
          cf api "${{ secrets.CF_API }}"
          cf auth "${{ secrets.CF_USERNAME }}" "${{ secrets.CF_PASSWORD }}" --client-credentials
          cf target -o "${{ secrets.CF_ORG }}" -s "${{ secrets.CF_SPACE }}"
          cf deploy ./pm-analyzer-fiori/mta_archives/comsappmpmanalyzerfiori_0.0.1.mtar -f