name: Deploy to SAP BTP Cloud Foundry

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a fresh Ubuntu environment for each job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Cloud Foundry CLI
        run: |
          wget -q -O cf-cli-installer.deb "https://packages.cloudfoundry.org/stable?release=debian64&version=8.7.6&source=github"
          sudo dpkg -i cf-cli-installer.deb
          cf version

      - name: Install Cloud Foundry MultiApps Plugin
        run: cf install-plugin -r CF-Community "multiapps" -f

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install MTA Build Tool (MBT)
        run: npm install -g mbt@1.2.0

      # --- Cloud Foundry Deployment Steps ---
      - name: Login to Cloud Foundry
        run: |
          cf api ${{ secrets.CF_API_ENDPOINT }}
          cf auth ${{ secrets.CF_USERNAME }} ${{ secrets.CF_PASSWORD }}
          cf target -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }}
        env:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_API_ENDPOINT: ${{ secrets.CF_API_ENDPOINT }}

      - name: Delete Existing Backend Application (if any)
        run: cf delete -f pm-analyzer-backend || true

      # --- MODIFIED: Push backend using the route from manifest.yml ---
      - name: Push Backend (without starting)
        run: |
          cd backend
          # The --no-route flag is REMOVED. CF will now use the route from manifest.yml.
          # The --no-start flag keeps the app stopped so we can set env vars before it runs.
          cf push pm-analyzer-backend -f manifest.yml --no-start

      # --- NEW: Set environment variable from GitHub Secret and restage ---
      - name: Set Google API Key for Backend
        run: cf set-env pm-analyzer-backend GOOGLE_API_KEY ${{ secrets.GOOGLE_API_KEY }}

      - name: Restage Backend to Apply Environment Variables
        # Restage will re-run the staging process and start the app, applying the new env var.
        # This replaces the old "cf start" step.
        run: cf restage pm-analyzer-backend

      # --- MTA steps for frontend remain the same ---
      - name: Build MTA Archive
        run: |
          mkdir -p mta_archives
          mbt build -p=cf --mtar mta_archives/com.sap.pm.pmanalyzer_1.0.0.mtar
          mv mta_archives/mta_archives/com.sap.pm.pmanalyzer_1.0.0.mtar mta_archives/

      - name: Deploy MTA Archive
        run: cf deploy mta_archives/com.sap.pm.pmanalyzer_1.0.0.mtar -f --retries 1