name: Build and Deploy to BTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pm-analyzer-backend:latest
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install MTA Build Tool
        run: npm install -g mbt

      - name: Build MTA
        run: mbt build -p=cf
        working-directory: ./pm-analyzer-fiori
        
      - name: Install CF CLI
        run: |
          wget -q -O cf-cli.tgz "https://github.com/cloudfoundry/cli/releases/download/v8.7.5/cf8-cli_8.7.5_linux_x86-64.tgz"
          tar -zxvf cf-cli.tgz
          sudo mv cf8 /usr/local/bin/cf
          cf --version
          
      - name: Install CF CLI MTA Plugin
        run: |
          # Add the Cloud Foundry community plugin repository
          cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org/
          # Install the multiapps-cli-plugin (MTA plugin)
          cf install-plugin -r CF-Community multiapps -f
          cf plugins # Verify the plugin is installed

      - name: Login and Deploy to BTP
        env:
          CF_API: ${{ secrets.CF_API }}
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
        run: |
          # Login with user credentials (no --client-credentials flag)
          cf login -a "$CF_API" -u "$CF_USERNAME" -p "$CF_PASSWORD" -o "$CF_ORG" -s "$CF_SPACE"
          
          # Deploy the application
          cf deploy ./pm-analyzer-fiori/mta_archives/comsappmpmanalyzerfiori_0.0.1.mtar -f
